sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t shan0325/react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true shan0325/react-app npm run test -- --coverage

after_success:
  - echo "Test success"

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "react-app"
  env: "DockerReactApp-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-972153559337"
  bucket_path: "react-app"
  on:
    branch: master
  access_key_id: $엑세스키
  secret_access_key: $시크릿키
